---
abstract: 'automatically run code after a fork'
author:
  - 'Jonathan Rockway C<< <jrockway@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hook-Fork
no_index:
  directory:
    - inc
    - t
requires:
  Guard: 0
  Sub::Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jrockway/hook-fork
version: 0.01_01
